### ISSUE TITLE
Make .expectErrors() return this

### ISSUE THREAD

**Issue by petrzjunior** [hirezio/observer-spy#46]
**Is your feature request related to a problem? Please describe.**
I really enjoy the concise way of writing single-expect tests
```js
expect(subscribeSpyTo(observable, { expectErrors: true }).getError()).toStrictEqual(error);
```
and this method mentioned is README is also very useful
```js
// BTW, this could also be set like this:
observerSpy.expectErrors(); // <-- ALTERNATIVE WAY TO SET IT
```
so I was thinking, why not to combine them?

**Describe the solution you'd like**
I suggest that `ObserverSpy.expectErrors()` would return `this`
```ts
expectErrors(): this {
    this.state.errorIsExpected = true;
    return this;
}
```
so that it is possible to write
```js
expect(subscribeSpyTo(observable).expectErrors().getError()).toStrictEqual(error);
```

**Comment by shairez** [comment]
Thanks @petrzjunior 

Personally I favor less nested calls and one-liners, but that's just my style

But I don't see an issue adding this line of code

If you can, please open a PR with tests, and I'll approve it

Thanks!

**Comment by shairez** [comment]
@petrzjunior 
OK I changed (locally) the test you wrote to reflect your needs - 

```
it('should allow single line style for expectErrors', () => {
   expect(subscribeSpyTo(throwError(() => FAKE_ERROR_MESSAGE)).expectErrors().getError()).toEqual(FAKE_ERROR_MESSAGE); 
})
```

And it doesn't really work... because the `expectErrors` need to be defind **before** the Observable is subscribed to... so it will probably only work  in cases there is an actual delay between values (which you wouldn't want to "wait for real" for those as this will make your tests slower...)

That's why you configure `expectErrors: true` when calling `subscribeSpyTo` and not after

So unless I'm missing something, I don't think this change will allow you to do what you need to do

**Comment by petrzjunior** [comment]
@shairez I'm afraid you are correct here. My actual use case is similar to what you wrote and it does not work as I expected, since the value is emitted in the same tick. I'm guessing the change is not that useful then, sorry.

**Comment by shairez** [comment]
No worries my friend, I completely missed that one as well
We can't learn if we don't try... :)

Thanks for the contribution!
